/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vaultSol from "./Vault.sol";
export type { vaultSol };
export type { AndamanToken } from "./AndamanToken";
