import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { AndamanToken__factory } from "../typechain-types";
import { useSigner } from "wagmi";
import { ethers } from "ethers";

const Home: NextPage = () => {
  const [totalSupply, setTotalSupply] = useState("0");
  const [mintInput, setMintInput] = useState("0");
  const { data: signer, isError, isLoading } = useSigner();

  const fetchTotalSupply = async () => {
    if (signer) {
      const andamanTokenContract = AndamanToken__factory.connect(
        "0x6e7A2dB6Ee481aBcabF6aD610A1b941e9B8CF7b5",
        signer
      );
      const totalSupply = await andamanTokenContract.totalSupply();
      setTotalSupply(ethers.utils.formatEther(totalSupply));
    }
  };

  const mint = async () => {
    if (signer) {
      const andamanTokenContract = AndamanToken__factory.connect(
        "0x6e7A2dB6Ee481aBcabF6aD610A1b941e9B8CF7b5",
        signer
      );
      const tx = await andamanTokenContract.mint(
        "0x92FA30D0A002863Bd6D9Bc968Aab853e5FA0d285",
        ethers.utils.parseEther(mintInput)
      );
      await tx.wait();
    }

  useEffect(() => {
    fetchTotalSupply();
  }, [signer]);

  return (
    <div className={styles.container}>
      <p>
        currentTotalSupply: {totalSupply} {isLoading && "loading..."}
      </p>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        {/* <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a className={styles.card} href="https://wagmi.sh">
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className={styles.card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
